#!/usr/bin/env python3
"""
Use a headless browser (Playwright) to log into YouTube and export cookies.txt.
Run this on the VPS — no GUI needed.

Install:
    pip install playwright
    playwright install chromium --with-deps
"""

import asyncio
import sys
from pathlib import Path
from playwright.async_api import async_playwright

OUTPUT = Path("cookies.txt")
YOUTUBE_URL = "https://www.youtube.com"


def to_netscape(cookies: list[dict]) -> str:
    lines = ["# Netscape HTTP Cookie File", "# Generated by generate_cookies.py", ""]
    for c in cookies:
        domain = c.get("domain", "")
        flag = "TRUE" if domain.startswith(".") else "FALSE"
        secure = "TRUE" if c.get("secure") else "FALSE"
        expires = int(c.get("expires", 0)) if c.get("expires") else 0
        name = c.get("name", "")
        value = c.get("value", "")
        path = c.get("path", "/")
        lines.append(f"{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{name}\t{value}")
    return "\n".join(lines)


async def login_and_export(email: str, password: str):
    async with async_playwright() as p:
        print("Launching headless Chromium...")
        browser = await p.chromium.launch(headless=True)
        context = await browser.new_context(
            user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                       "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
        )
        page = await context.new_page()

        print("Navigating to Google login...")
        await page.goto("https://accounts.google.com/signin/v2/identifier?service=youtube")
        await page.wait_for_load_state("networkidle")

        # Enter email
        print("Entering email...")
        await page.fill('input[type="email"]', email)
        await page.click('#identifierNext')
        await page.wait_for_timeout(2000)

        # Enter password
        print("Entering password...")
        await page.fill('input[type="password"]', password)
        await page.click('#passwordNext')
        await page.wait_for_timeout(3000)

        # Navigate to YouTube to trigger YouTube-specific cookies
        print("Loading YouTube...")
        await page.goto(YOUTUBE_URL)
        await page.wait_for_load_state("networkidle")
        await page.wait_for_timeout(2000)

        # Check login success
        url = page.url
        if "accounts.google.com" in url:
            print("ERROR: Login failed — still on Google accounts page.")
            print("Possible causes: wrong credentials, 2FA required, or Google blocked the login.")
            await browser.close()
            sys.exit(1)

        print("Logged in. Extracting cookies...")
        cookies = await context.cookies()
        yt_cookies = [c for c in cookies if "youtube.com" in c.get("domain", "") or "google.com" in c.get("domain", "")]

        OUTPUT.write_text(to_netscape(yt_cookies))
        print(f"Saved {len(yt_cookies)} cookies to {OUTPUT.resolve()}")

        await browser.close()


def main():
    print("=== YouTube Headless Cookie Generator ===\n")
    email = input("Google email: ").strip()
    password = input("Password: ").strip()

    if not email or not password:
        print("Email and password are required.")
        sys.exit(1)

    asyncio.run(login_and_export(email, password))
    print("\nDone. Use cookies.txt with yt-dlp:")
    print("  yt-dlp --cookies cookies.txt <url>")


if __name__ == "__main__":
    main()
